name: Release VS Code Extension

on:
  push:
    branches:
      - main # Run on pushes to the main branch
    tags:
      - 'v*' # Also run on pushes to tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission to GITHUB_TOKEN for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use Node.js 20.x to avoid EBADENGINE warning

    - name: Install dependencies
      run: npm install

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Package extension
      run: vsce package

    - name: Get Package Version
      id: get_version
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./commitify-${{ env.PACKAGE_VERSION }}.vsix
        asset_name: commitify-${{ github.ref_name }}.vsix
        asset_content_type: application/octet-stream